### ISSUE TITLE
Problem with install 

### ISSUE THREAD

**Issue by M7-Robotics** [rajeshsola/node-red-addons#3]
Hi,

I am having problems with installing this node, and really wish to use it. Can you please help?

Here is the messages that are returned when issuing the install command:

`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/node-red-contrib-usb failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> usb@1.3.1 install /home/oem/.node-red/projects/SMAC/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@8.11.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/oem/.node-red/projects/SMAC/node_modules/usb/build'
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/oem/.node-red/projects/SMAC/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/oem/.node-red/projects/SMAC/node_modules/usb/src/binding"
gyp ERR! cwd /home/oem/.node-red/projects/SMAC/node_modules/usb
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/oem/.node-red/projects/SMAC/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/oem/.node-red/projects/SMAC/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/oem/.node-red/projects/SMAC/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.10.0-38-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/oem/.node-red/projects/SMAC/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/oem/.node-red/projects/SMAC/node_modules/usb
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/oem/.node-red/projects/SMAC/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/oem/.node-red/projects/SMAC/node_modules/usb/src/binding' (1)
npm WARN SMAC@0.0.1 No repository field.
npm WARN SMAC@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oem/.npm/_logs/2018-06-08T07_33_07_341Z-debug.log
`

**Comment by Bobet21** [comment]
see #4 and #5 to solve this issue
